import { CfnOutput, Duration, Stack, StackProps } from "aws-cdk-lib";
import {
  Effect,
  OpenIdConnectProvider,
  PolicyStatement,
  Role,
  WebIdentityPrincipal,
} from "aws-cdk-lib/aws-iam";
import { Construct } from "constructs";

export interface GithubOidcStackProps extends StackProps {
  /** `owner/name` of the repository allowed to deploy. */
  readonly repository: string;
  /** Only this branch may assume the deploy role. */
  readonly deploymentBranch: string;
  readonly siteBucketName: string;
}

const GITHUB_ISSUER_URL = "https://token.actions.githubusercontent.com";
const GITHUB_ISSUER_DOMAIN = "token.actions.githubusercontent.com";
const AWS_STS_AUDIENCE = "sts.amazonaws.com";
const CDK_BOOTSTRAP_QUALIFIER = "hnb659fds";
const CDK_BOOTSTRAP_ROLES = ["deploy", "file-publishing", "image-publishing", "lookup"];

/**
 * Trust between GitHub Actions and this AWS account. Deployed once by an
 * operator; the workflow then assumes {@link GithubOidcStack.deployRole} with a
 * short-lived token instead of stored access keys.
 */
export class GithubOidcStack extends Stack {
  constructor(scope: Construct, id: string, props: GithubOidcStackProps) {
    super(scope, id, props);

    const provider = new OpenIdConnectProvider(this, "GithubProvider", {
      url: GITHUB_ISSUER_URL,
      clientIds: [AWS_STS_AUDIENCE],
    });

    const deployRole = new Role(this, "DeployRole", {
      roleName: "elemwave-staging-github-deploy",
      description: `Deploys the marketing site to staging from ${props.repository}@${props.deploymentBranch}`,
      maxSessionDuration: Duration.hours(1),
      assumedBy: new WebIdentityPrincipal(provider.openIdConnectProviderArn, {
        StringEquals: {
          [`${GITHUB_ISSUER_DOMAIN}:aud`]: AWS_STS_AUDIENCE,
          [`${GITHUB_ISSUER_DOMAIN}:sub`]: `repo:${props.repository}:ref:refs/heads/${props.deploymentBranch}`,
        },
      }),
    });

    deployRole.addToPolicy(
      new PolicyStatement({
        sid: "AssumeCdkBootstrapRoles",
        effect: Effect.ALLOW,
        actions: ["sts:AssumeRole"],
        resources: this.cdkBootstrapRoleArns(),
      }),
    );

    deployRole.addToPolicy(
      new PolicyStatement({
        sid: "PublishSiteContent",
        effect: Effect.ALLOW,
        actions: [
          "s3:ListBucket",
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:GetBucketLocation",
        ],
        resources: [`arn:aws:s3:::${props.siteBucketName}`, `arn:aws:s3:::${props.siteBucketName}/*`],
      }),
    );

    deployRole.addToPolicy(
      new PolicyStatement({
        sid: "InvalidateStagingCache",
        effect: Effect.ALLOW,
        // Distribution ids are generated by CloudFront, so they cannot be
        // written into a policy that is deployed before the distribution exists.
        actions: ["cloudfront:CreateInvalidation", "cloudfront:GetInvalidation", "cloudfront:ListDistributions"],
        resources: ["*"],
      }),
    );

    new CfnOutput(this, "DeployRoleArn", {
      value: deployRole.roleArn,
      description: "Store this as the AWS_DEPLOY_ROLE_ARN repository secret",
    });
  }

  /**
   * The roles `cdk bootstrap` creates in each region the app deploys to. The
   * certificate lives in us-east-1, everything else in the primary region.
   */
  private cdkBootstrapRoleArns(): string[] {
    const regions = [this.region, "us-east-1"];
    const uniqueRegions = Array.from(new Set(regions));

    return uniqueRegions.flatMap((region) =>
      CDK_BOOTSTRAP_ROLES.map(
        (role) => `arn:aws:iam::${this.account}:role/cdk-${CDK_BOOTSTRAP_QUALIFIER}-${role}-role-${this.account}-${region}`,
      ),
    );
  }
}
